version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_ROOT_PASSWORD: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"