version: '3'

services:
  auth_microservice:
    container_name: auth_microservice
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    ports:
      - "3306:3306"
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
