version: '3'

services:
  auth_microservice:
    container_name: auth_microservice
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - ./:/app

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
